### PR TITLE
Service Instantiation - Changing timeout limit to 15 min

### PR DESCRIPTION
**Pull request by srodriguezOPT**

### CODE REVIEW

**Comment by jbonnet** [comment]
@srodriguezOPT Could you make this value (15mins) be passed through an environment variable?

**Comment by jbonnet** [comment]
@srodriguezOPT Also, where is this timeout applied? Wouldn't (not for Y1!) an AJAX approach work better?

**Comment by srodriguezOPT** [comment]
This timeout applies in the protractor test of the E2E service instantiation.
browser.wait(EC.textToBePresentInElement(element(by.repeater("InstantiationRequest in InstantiationRequests").column('status')) ,'ready', 900000));

In instantiation request section, the browser looks for a status change to "ready" during a maximum of 15 min. When request changes to ready the test ends successfully but after 15 minutes, if request doesn't be ready, the test is marked as failed.

**Comment by jbonnet** [comment]
Ah, ok, so it's not in the normal operation of the BSS app... that's good, please ignore my second comment... ;-)

**Pull request merged**
